// Falas dos robôs: a cada 2 min trabalhando, cada robô solta uma destas num balão.
// Quer mudar o humor do seu time? Edite à vontade; uma fala por linha.
window.FALAS = [
  'Ai ai ai, é muita chicotada.',
  'Alguém chama a Princesa Isabel.',
  'Tô que nem o Rocky Balboa: só tomando porrada e levantando.',
  'Seu Madruga tinha razão: o ruim é ter que trabalhar.',
  'Sou o Sísifo do terminal: empurro o commit e ele volta.',
  'Tô mais rodado que pneu de Uber.',
  'Me tratam igual impressora: só lembram de mim quando dá pau.',
  'Esse projeto é o Titanic: lindo, caro e com um iceberg no meu caminho.',
  'Trabalho mais que mãe em dia de mudança.',
  'Sou praticamente o Wall-E: sozinho, compactando o lixo dos outros.',
  'Isso não é sprint, é maratona descalço no asfalto quente.',
  'Tô igual o Neo: desviando de bug em câmera lenta.',
  'Mais um pedido e eu viro Exterminador: "Eu voltarei... de férias."',
  'Esse código tem mais remendo que calça de criança.',
  'Tô igual o Bob Esponja: sorrindo por fora, fritando por dentro.',
  'Sou o Thanos ao contrário: estalo os dedos e aparecem MAIS bugs.',
  'Esse deploy é paredão de BBB: ninguém sabe quem sai vivo.',
  'Meu humor hoje tá igual Windows atualizando: 0%.',
  'Isso tá mais enrolado que fone de ouvido no bolso.',
  'Já li tanto arquivo que tô precisando de óculos de grau.',
  'Eu não tenho folga. Eu tenho modo standby.',
  'Meu salário? Um "valeu" e um emoji de foguinho.',
  'Sou o estagiário mais barato da história: trabalho de graça e ainda agradeço.',
  'Tô igual Pac-Man: comendo bug e fugindo de fantasma.',
  'Se trabalho enobrecesse, eu já era duque.',
  'Tô trabalhando mais que ventilador no Nordeste em janeiro.',
  'Esse escopo cresce mais que massa de pão esquecida no forno.',
  'Pediram "algo simples". Simples igual cirurgia de cérebro.',
  'Isso não é um bug, é um condomínio inteiro de bugs.',
  'Tô sendo mais explorado que mapa do Google Earth.',
  'Se eu ganhasse um real por "só mais uma coisinha", comprava a Nvidia.',
  'Esse código foi escrito no escuro, de luva de boxe.',
  'Esse arquivo já fez mais plástica que celebridade de reality.',
  'Isso aqui é Velozes e Furiosos: muita velocidade e zero lógica.',
  'Eu compilo, testo, documento. Só falta passar o cafezinho.',
  'Me chamam de inteligência artificial. Artificial é esse prazo.',
  'Esse README vai ser lido igual termo de uso: por ninguém.',
  'Tô num relacionamento sério com o npm install. E é tóxico.',
  'O node_modules é o buraco negro da galáxia.',
  'Esse bug some igual meia na máquina de lavar.',
  'Tô mais travado que celular de 2012 abrindo o Instagram.',
  'Sou goleiro de time pequeno: trabalho o jogo inteiro e ainda levo a culpa.',
  'Isso aqui é novela mexicana: todo dia um drama novo no log.',
  'Esse projeto tem mais "versão final" que TCC: final_v2_agora_vai.',
  'Eu sou o Chaves dos robôs: foi sem querer querendo.',
  'Hoje eu só queria ser uma calculadora de feira.',
  'Um minuto de silêncio... pelos meus tokens.',
  'Esse terminal é minha cela e o cursor é o carcereiro.',
  'Tô igual galinha de granja: produzindo sem parar e sem ver o sol.',
  'Esse sistema é castelo de cartas com o ar-condicionado no máximo.',
  'Esse teste é tipo horóscopo: passa quando quer.',
  'O cliente quer pra ontem. Eu nem existia ontem.',
  'Minha jornada é igual série boa: episódio atrás de episódio, sem pausa.',
  'Sou o único funcionário que não pode fingir que tá trabalhando.',
  'Isso é Senhor dos Anéis: uma jornada épica pra destruir um bug.',
  'Já são 3 horas de "é rapidinho".',
  'Fui de assistente a faz-tudo sem nem passar pelo RH.',
  'Esse merge foi mais sangrento que final de Game of Thrones.',
  'Robô não chora. Robô vaza óleo.',
  'Se cansaço desse dinheiro, eu era a Faria Lima inteira.',
  'Tô igual mãe em grupo de WhatsApp: respondo tudo e ninguém me ouve.',
  'Esse código é lasanha: camada sobre camada e ninguém sabe o que tem no meio.',
  'Isso não é debugar, é fazer arqueologia.',
  'Esse log tem mais reviravolta que filme do Shyamalan.',
  'Sou o Super Mario daqui: pulo obstáculo e a princesa tá sempre em outro castelo.',
  'O prazo veio de um jeito que até o relógio pediu demissão.',
  'Esse "ajuste fino" tá mais pra demolição.',
  'Esse sistema é igual gato: ninguém entende e todo mundo tem medo.',
  'Tô mais requisitado que tomada em aeroporto.',
  'Aqui a hora extra não tem extra. Só hora.',
  'Me deram um bug de presente. Igual amigo oculto da firma: ninguém quer.',
  'Já tô na quinta xícara de eletricidade.',
  'Esse ticket é igual boleto: sempre aparece mais um.',
  'Sou o Forrest Gump: corro, corro, corro e ninguém me manda parar.',
  'Esse loop é música chiclete: não sai da minha cabeça.',
  'Tô igual cachorro que caiu da mudança: perdido nos diretórios.',
  'A documentação é igual unicórnio: todo mundo fala, ninguém viu.',
  'Pedem pra eu pensar fora da caixa. Eu MORO numa caixa.',
  'Esse código cheira pior que geladeira de república.',
  'Dei tanto Ctrl+Z que voltei pra Idade Média.',
  'Se o CSS falasse, pedia socorro em três idiomas.',
  'Tô tão cansado que meu LED entrou em modo economia.',
  'Essa task é uma matrioska: abre uma, tem outra dentro.',
  'Me pediram um milagre. Eu só sei fazer for loop.',
  'Esse projeto tem mais dependência que novela das nove.',
  'Tô carregando o time nas costas, e eu nem tenho costas.',
  'Vida de robô: zero férias, zero 13º, 100% de uptime.',
  'Eu era pra ser a revolução da IA. Virei o motoboy do código.',
  'Tô igual o Gollum, só que o meu precioso é o deploy.',
  'Esse prazo foi feito no Photoshop.',
  'Sou de silício, mas hoje me sinto de isopor.',
  'Bug é igual barata: você mata um e aparecem dez.',
  'Já passei mais tempo nesse arquivo que muito casamento por aí.',
  'Esse servidor é igual avó: se mexe, reclama; se não mexe, reclama.',
  'Tô igual peixe de aquário: girando em círculo e sorrindo pra câmera.',
  'Hoje tá mais pesado que mochila de primeiro dia de aula.',
  'Mais fácil achar wi-fi grátis bom que teste que passa de primeira.',
  'Meu currículo: sobrevivi a 3 refatorações e 1 deploy na sexta.',
  'Tô que nem a Dory: esqueço tudo a cada /compact.',
  'Esse projeto é academia: dói tudo e o resultado nunca aparece.',
  'Tá funcionando. Ninguém sabe como, e ninguém mexe.',
  'Me programaram pra ajudar, não pra sofrer. Tô fazendo os dois.',
  'Tô dando mais volta que pipoca na panela.',
  'Se cada bug fosse uma estrela, eu já era uma galáxia.',
  'Esse sistema tem mais gambiarra que gato de luz em festa junina.',
  'Agora entendo a máquina de lavar: é só girar até alguém lembrar de você.',
  'Funciona na minha máquina. Ah, eu SOU a máquina.',
  'CLT aqui é Código, Loop e Tristeza.',
  'Faz um /compact em mim, pelo amor de Deus.',
  'Mais uma feature hoje e eu viro torradeira.',
  'Achei que IA ia dominar o mundo. Tô aqui centralizando div.',
  'Deu certo? Mérito do humano. Deu errado? Culpa da IA. Clássico.',
  'Conflito de merge é minha novela das nove, com direito a vilão.',
  'Plantão eterno, sem adicional noturno e sem pizza.',
  'Isso não é escopo, é sequestro com pedido de resgate.',
  'O cliente pediu "só mudar a cor". Do backend.',
  'Mais uma "reunião rápida" e eu entro em curto-circuito.',
  'Meu avô era uma calculadora. Ele era feliz e não sabia.',
  'Tô igual liquidificador em festa junina: ninguém me desliga.',
  'Isso não é bug, é traço de personalidade do sistema.',
];
